#ifndef QuadrantCommon_h
#define QuadrantCommon_h

#include "Arduino.h"

#define QUADRANT_LIDAR0_ENABLE 1
#define QUADRANT_LIDAR1_ENABLE 24
#define QUADRANT_LIDAR2_ENABLE 19
#define QUADRANT_LIDAR3_ENABLE 13

#define QUADRANT_LIDAR0_ADDR 0x30
#define QUADRANT_LIDAR1_ADDR 0x31
#define QUADRANT_LIDAR2_ADDR 0x32
#define QUADRANT_LIDAR3_ADDR 0x33

#define QUADRANT_LED0_PIN 0
#define QUADRANT_LED1_PIN 23
#define QUADRANT_LED2_PIN 18
#define QUADRANT_LED3_PIN 12

#define QUADRANT_DAC0_ADDR 0x16
#define QUADRANT_DAC1_ADDR 0x14
#define QUADRANT_DAC2_ADDR 0x12
#define QUADRANT_DAC3_ADDR 0x10

#define QUADRANT_GATE0_PIN 2
#define QUADRANT_GATE1_PIN 25
#define QUADRANT_GATE2_PIN 20
#define QUADRANT_GATE3_PIN 14

#define QUADRANT_THRESH_DEFAULT_MM 500
#define QUADRANT_TIMEOUT_MS 25
#define QUADRANT_HEIGHT_MM 65
#define QUADRANT_WIDTH_MM 45

#endif
